# SERVERS
FILESERVER = 5000
DIRECTORYSERVER = 5001
LOCKSERVER = 5002
REPLICATIONSERVER = 5003
CACSERVER = 5004

# VARIABLES
LOCKATTEMPT = 1
REPLICATIONSERVER = 2
REPSERVERCOPIES = 5

# Client and directory server connection
REQUESTFILEDETAIL = 'REQUESTFILEDETAIL: {}\nDIRECTORY: {}\nACTION: {}\n\n'
RETURNFILEDETAIL = 'RETURNFILEDETAIL: {}\nIP: {}\nPORT: {}\n\n'

# client/replication server and lock server communication
REQUESTLOCK = 'REQUESTLOCK: {}\nCLIENT: {}\n\n'
REQUESTUSE = 'REQUESTUSE: {}\nCLIENT: {}\n\n'
REQUESTUNLOCK = 'REQUESTUNLOCK: {}\nCLIENT: {}\n\n'

# Client and Replication Server Communication
WRITEFILE = 'WRITEFILE: {}\nCLIENT: {}\nDATA: {}\n\n'
READFILE = 'READFILE: {}\nCLIENT: {}\n\n'
DELETEFILE = 'DELETEFILE: {}\nCLIENT: {}\n\n'
RETURNFILEDATA = 'RETURNFILEDATA: {}\n\n'

# Status 
SUCCESS = 'SUCCESS: {}\n\n'
FAILURE = 'FAILURE: {}\n\n'
ERRORMSG = 'ERRORMSG: {}\n\n'
